on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build site with Zola
        # run: zola build
        # Или, если zola не установлен:
        run: |
           curl -sSf https://get.zola.rs | sh
           ./zola build

      - name: Create CNAME
        run: echo "brain4bi.org" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public